apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURBVENDQWVtZ0F3SUJBZ0lKQUx0NW45OG5EWXRlTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmN4RlRBVEJnTlYKQkFNTURERXdMakUxTWk0eE9ETXVNVEFlRncweU1EQTRNekV3TWpVME5EQmFGdzB6TURBNE1qa3dNalUwTkRCYQpNQmN4RlRBVEJnTlZCQU1NRERFd0xqRTFNaTR4T0RNdU1UQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQCkFEQ0NBUW9DZ2dFQkFPU2pPRU5lWWZIQjU1L1VPVUx6RTZzZVR0U0g0T0VmWHExOTNvak0yenF3QmQ0ZjI1T1kKbjNQeFpic1o1NUhiVnBST2VSb3lIQXhSV2hPVzZTS1FqM09uNGNVR2lTZTFkcEdQUjFsQTNkUEdLeCthYS81NApoRCsxcncxT2NYZWlrL0JydUR6cE0zZDRUNW4rZWV3TGNSTngvQWdKZlhReWZuUFdua1cvNW9hQmxhZWV2V1RXCmd0VGcvRSt0N2tIS2xtNGRrT0U1YWEwdlVZK283WW9UNjJFYlFwRnNrTHlqbVVsQW5zTXJWSXpKRW1aa2dTWTQKa3JZUC9CZW91WjFqMWt2QzVFcWxwYmRDd0dlVmlxUFQ5N2ovbWZiaFBHU2lUU0FSeDVsNzQrQTlmQ2c3SHArdAo3ZFJHc0V5eFg5QUErRTUweVpIYldQWUZEYUVmRDJUWFJmY0NBd0VBQWFOUU1FNHdIUVlEVlIwT0JCWUVGRjFSCi9uVmdWNnhTOTJZYm5zZVdFOStNU3FFcU1COEdBMVVkSXdRWU1CYUFGRjFSL25WZ1Y2eFM5MllibnNlV0U5K00KU3FFcU1Bd0dBMVVkRXdRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUw3eHVKZXowSE1hS0hqRQowNlF6Ti9jR0paMGcvdlVYZVo0bmJ0aHJWbGpoSmRrTVh1STErWDFoT2hEN01FK0tjbDloR0ZBY3Q3b1JCR2xJCjhEZzVNaHZhbFNsbko2Q2F2Uy9Nd25aMTNPWGZzWFpzUHhiNERZL001L0ZOSWxMTURLZDBHM1hTenoxZ3NkbWMKdUNvay81V2k5ZjNoNkhVODNFRFlqclpUQlVROEk3SDhUWjRYT1JSS3NndXgvS0s2TzJ1YzR2TnFtcXM3c0ZYeAord1NwR3NTeXV5aVo1dFhHVm5RdUxyK2VsMnNESi9lZ2R4LytRS29wNTU0M0JiczdyODl1VnhYWGZxSzRZYUtJCmlxZzF2MTI0VFNjSTQ1SVpUb2pmVFM3eUl6T3huaXBweDFFdXdUUitLTk1vR09PS0RaMGZsMWwybjJKa1pzSTgKUEhmQUJ5TT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://172.16.12.201:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: civo
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: SHlzcU9nd0ZXUnh0RDZrWWdzTW0xQU9IWGFsdEQwQWVPL3dUc0t3RDBpdz0K
