os:
  openCommand: code -rg {{filename}}
customCommands:
  - key: C
    command: git cz c
    context: files
    loadingText: opening commitizen commit tool
    subprocess: true
  - key: N
    command: git commit -m "regular update [$(gdate -u -Isecond)]"
    context: files
    loadingText: git commit now with timestamp
  - key: M
    command: git mergetool {{ .SelectedFile.Name }}
    context: files
    loadingText: opening git mergetool
    subprocess: true
  - key: <c-p>
    command: git remote prune {{.SelectedRemote.Name}}
    context: remotes
    loadingText: Pruning...
    description: prune deleted remote branches
